package com.microservices.serviceone.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BrigadeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrigadeAllPropertiesEquals(Brigade expected, Brigade actual) {
        assertBrigadeAutoGeneratedPropertiesEquals(expected, actual);
        assertBrigadeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrigadeAllUpdatablePropertiesEquals(Brigade expected, Brigade actual) {
        assertBrigadeUpdatableFieldsEquals(expected, actual);
        assertBrigadeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrigadeAutoGeneratedPropertiesEquals(Brigade expected, Brigade actual) {
        assertThat(expected)
            .as("Verify Brigade auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrigadeUpdatableFieldsEquals(Brigade expected, Brigade actual) {
        assertThat(expected)
            .as("Verify Brigade relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getEstablishedYear()).as("check establishedYear").isEqualTo(actual.getEstablishedYear()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrigadeUpdatableRelationshipsEquals(Brigade expected, Brigade actual) {
        assertThat(expected)
            .as("Verify Brigade relationships")
            .satisfies(e -> assertThat(e.getGovernorate()).as("check governorate").isEqualTo(actual.getGovernorate()));
    }
}
